### ISSUE TITLE
Show zombie processes in debugger

### ISSUE THREAD

**Issue by reberhardt7** [reberhardt7/cplayground#17]
The debugger has a pane that lists running processes:
![Screen Shot 2020-03-24 at 9 09 40 PM](https://user-images.githubusercontent.com/4855412/77501832-5d303e00-6e16-11ea-92c2-a087ac14a447.png)

Say the user forks off a child process; the child process exits, but the parent process is still running and has not yet called `waitpid()` on the child. The child process is then a *zombie process*; it still exists, even though it has terminated. As such, we should list that zombie process in the process listing. (This is important because cplayground is used in an educational setting where we help students new to multiprocessing learn how to reap processes and avoid resource leaks.)

The data for the process listing comes from two places: `/proc/cplayground` (a file generated by our kernel module) and gdb. I am pretty sure `/proc/cplayground` does not currently include zombie processes, so we'll have to change that. (I believe [this](https://github.com/reberhardt7/cplayground/blob/aa07b66af975df940979d77f1cd7ee9fb5a065c2/src/server/kernel-mod/cplayground.c#L184) skips over zombies so that we can get the process namespace. If true, we need some other way to get the process's PID namespace. But this code is rusty in my head.) Then, we'll need to change the [code that integrates the procfile data with gdb data](https://github.com/reberhardt7/cplayground/blob/3bba190888f1f06f48de5af4b0583dfe1297294b/src/server/debugging.ts#L508). Right now, it omits processes that don't show up in gdb, but we wouldn't want to do that because we want to keep the zombie processes (even though they're no longer gdb inferiors).

**Comment by thorerikflekkum** [comment]
😈

**Comment by thorerikflekkum** [comment]
👿

**Comment by thorerikflekkum** [comment]
😈👿cjkgg

**Comment by glen3b** [comment]
Potentially relevant: [`fs/proc/namespaces.c`](https://elixir.bootlin.com/linux/latest/source/fs/proc/namespaces.c) in the kernel source tree. I haven't looked or poked much, but my uneducated guess would be that this is responsible for `/proc/<PID>/ns`, which I have confirmed works correctly for PID namespaces for zombie process.

**Comment by glen3b** [comment]
I've given [getting zombie namespaces](https://github.com/glen3b/cplayground/commit/5bcddec062272ff4612d235fcd128e273975eb7f) a crack and it looks fairly straightforward, next I'll look at backend and frontend changes. Is there any change that would be needed or desired on the frontend? (I still have to familiarize myself with the userspace parts of this project, but I'm working in that direction.)

Here's some outputs just to note them down.

<details>
<summary>Example "kernel data" dump from web server logfile:</summary>

PIDs 19 and 20 are zombies. Program simply `fork`ed twice.

```js
{
  processes: [
    {
      debuggerId: 1,
      pid: 14,
      ppid: 12,
      pgid: 14,
      command: 'cplayground',
      threads: [Array],
      fds: [Object]
    },
    {
      debuggerId: 2,
      pid: 18,
      ppid: 14,
      pgid: 14,
      command: 'cplayground',
      threads: [Array],
      fds: [Object]
    },
    {
      debuggerId: null,
      pid: 19,
      ppid: 18,
      pgid: 14,
      command: 'cplayground',
      threads: [],
      fds: {}
    },
    {
      debuggerId: null,
      pid: 20,
      ppid: 14,
      pgid: 14,
      command: 'cplayground',
      threads: [],
      fds: {}
    }
  ],
  openFiles: {
    '782480e0daf944401eba0eaf93b79e2b444f4a04465331f4b85ebb9b85985c34': { position: 0, flags: [Array], refcount: 6, vnode: '/dev/pts/0' }
  },
  vnodes: { '/dev/pts/0': { name: '/dev/pts/0', refcount: 1 } }
}
```
</details>

<details>
<summary>Process list in interface:</summary>

![Process list](https://user-images.githubusercontent.com/3952667/87126411-fb6ad700-c240-11ea-8f07-087bc24a9498.png)
</details>

<details>
<summary>File diagram in interface:</summary>

![File diagram](https://user-images.githubusercontent.com/3952667/87126428-032a7b80-c241-11ea-9592-a9787589b080.png)
</details>

This is all with just the kernel module tweak. Do these look right?
