### ISSUE TITLE
Add license to repository

### ISSUE THREAD

**Issue by glen3b** [reberhardt7/cplayground#44]
This repository doesn't have a license file, so it's unclear what terms others can use this project under or what terms contributors are contributing their work under.

Per discussions in the development Slack, not having a license is simply an oversight; according to Choose A License, not having one is [probably not what we want](https://choosealicense.com/no-permission/).

I'm creating this issue to track the ToDo so it doesn't get lost.

In terms of the actual licence in question, I have a slight preference for copyleft for non-libraries, especially something educational like this, but I'm fine with anything FOSS. I only chip in here as my 2 cents; @reberhardt7 should make this call.

**Comment by reberhardt7** [comment]
Thanks for following up on this!
